---
name: Checks

on:
    push:
        branches: main


jobs:
    test-lint:
        name: Test and lint
        runs-on: ubuntu-20.04
        steps:
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}   
                    password: ${{ secrets.DOCKERHUB_PAT }}
            - 
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Test
                run: docker compose run --rm app sh -c "python3 manage.py test"
            - 
                name: Lint
                run: docker compose run --rm app sh -c "flake8"
